#!/usr/bin/env node
/**
 * Generate daily diary from OpenClaw conversation history
 * Usage: node generate-diary.js <YYYY-MM-DD>
 */

const fs = require('fs');
const path = require('path');

// Configuration - adjust these paths for your setup
const SESSIONS_DIR = process.env.OPENCLAW_SESSIONS_DIR || 
  path.join(require('os').homedir(), '.openclaw/agents/main/sessions');
const DIARY_DIR = process.env.DIARY_OUTPUT_DIR || 
  path.join(process.cwd(), 'memory', 'diary');

function getTargetDate() {
  const args = process.argv.slice(2);
  if (args[0]) return args[0];
  
  // Default: yesterday
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toISOString().split('T')[0];
}

function findSessionFiles(targetDate) {
  if (!fs.existsSync(SESSIONS_DIR)) {
    console.error(`Sessions directory not found: ${SESSIONS_DIR}`);
    return [];
  }
  
  const files = fs.readdirSync(SESSIONS_DIR);
  const jsonlFiles = files.filter(f => f.endsWith('.jsonl') && !f.includes('.lock'));
  
  const targetFiles = [];
  
  for (const file of jsonlFiles) {
    const filePath = path.join(SESSIONS_DIR, file);
    const stats = fs.statSync(filePath);
    const fileDate = stats.mtime.toISOString().split('T')[0];
    
    // Also check file content for timestamps
    try {
      const content = fs.readFileSync(filePath, 'utf8').split('\n')[0];
      if (content) {
        const firstLine = JSON.parse(content);
        if (firstLine.timestamp) {
          const contentDate = firstLine.timestamp.split('T')[0];
          if (contentDate === targetDate) {
            targetFiles.push(filePath);
            continue;
          }
        }
      }
    } catch (e) {}
    
    if (fileDate === targetDate) {
      targetFiles.push(filePath);
    }
  }
  
  return targetFiles;
}

function parseSessionFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n').filter(l => l.trim());
  
  const messages = [];
  for (const line of lines) {
    try {
      const entry = JSON.parse(line);
      if (entry.type === 'message' && entry.message) {
        const role = entry.message.role;
        const text = entry.message.content?.[0]?.text || '';
        if (text && text.length > 10) {
          messages.push({ role, text: text.substring(0, 500) });
        }
      }
    } catch (e) {}
  }
  
  return messages;
}

function generateDiary(targetDate, conversations) {
  // This is a template - the actual content should be generated by AI
  const diary = `# Daily Diary · ${targetDate}

> "Memory is not a drawer of files, but reflections in a flowing river."

## Today in Review

${conversations.length > 0 
  ? `Today we had ${conversations.length} conversation sessions.` 
  : 'A quiet day with fewer conversations.'}

${conversations.slice(0, 5).map((conv, i) => {
  const userMsgs = conv.filter(m => m.role === 'user').length;
  const assistantMsgs = conv.filter(m => m.role === 'assistant').length;
  return `- Session ${i+1}: ${userMsgs} messages from user, ${assistantMsgs} responses`;
}).join('\n')}

## What I Learned

[AI to fill in based on actual conversation content]

## Observations

[Insights about interactions and patterns]

## My Growth

[Personal evolution as an AI agent]

## Reflections

[Philosophical musings, deeper thoughts]

---

*Written ${targetDate}*
`,
  
  return diary;
}

function main() {
  const targetDate = getTargetDate();
  console.log(`Generating diary for: ${targetDate}`);
  
  // Ensure diary directory exists
  if (!fs.existsSync(DIARY_DIR)) {
    fs.mkdirSync(DIARY_DIR, { recursive: true });
  }
  
  // Find and parse session files
  const sessionFiles = findSessionFiles(targetDate);
  console.log(`Found ${sessionFiles.length} session files`);
  
  if (sessionFiles.length === 0) {
    console.log('No sessions found for this date.');
  }
  
  const conversations = sessionFiles.map(parseSessionFile);
  
  // Generate diary template
  const diary = generateDiary(targetDate, conversations);
  
  // Save diary
  const diaryPath = path.join(DIARY_DIR, `${targetDate}.md`);
  fs.writeFileSync(diaryPath, diary);
  console.log(`Diary template saved to: ${diaryPath}`);
  console.log('Note: This is a template. AI should read and generate actual content.');
  
  return diaryPath;
}

if (require.main === module) {
  main();
}

module.exports = { generateDiary, findSessionFiles, parseSessionFile };
